<?php

defined('ROOT' )|| die('Restricted Access');

?><?php
echo $errors->first();
echo Form::open(array('url' => '/settings', 'method' => 'POST','class'=>'form-horizontal'));
?>

<div class="well">
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">

<?php
                echo "<fieldset>";
    echo Form::label('schoolname','School Name',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::text('schoolname',Setting::get('system.schoolname'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;margin:10px;'));
    echo Form::label('schoolnameabbr','School Name Abbreviation',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::text('schoolnameabbr',Setting::get('system.schoolnameabbr'),array('class'=>'col-lg-6-input-small form-control input-sm pull-right','style'=>'width:120px;margin:5px;'));
    echo Form::label('schooladdress','School Address',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::textarea('schooladdress',Setting::get('system.schooladdress'),array('class'=>'form-control input-sm pull-right','style'=>'width:240px;margin:5px;','rows'=>'2'));
    echo Form::label('logo','Logo Path',array('class'=>'pull-left','style'=>'clear:left;margin-top:40px;'));
    echo Form::text('logo',Setting::get('system.logo_src'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;margin:5px;'));
    echo Form::label('adminsitename','Admin Site Name',array('class'=>'pull-left','style'=>'clear:left;margin-top:20px;'));
    echo Form::text('adminsitename',Setting::get('system.adminsitename'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;margin:5px;'));
?>

</div>
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
<?php
    echo Form::label('url','Domain',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::text('url',Setting::get('app.url'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;'));

    echo Form::label('captcha','Captcha',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::select('captcha',
        ['captcha'=>'System Generated Captcha',
         'recaptcha'=>'Service using reCaptcha API',
         'checkbox'=>'CheckBox Captcha generated by System using Built-In Logics'],'recaptcha',array('class'=>'form-control input-sm pull-right','style'=>'width:240px;'));   

    echo Form::label('systemurl','Dashboard Domain',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::text('systemurl',Setting::get('system.dashurl'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;'));
    echo Form::label('systemurlshort','Dashboard Domain Short',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::text('systemurlshort',Setting::get('system.dashurlshort'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;'));
    echo Form::label('siteurlshort','Site Domain Short',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::text('siteurlshort',Setting::get('system.siteurlshort'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;'));  
      echo Form::label('Cache','Cache Max Life',array('class'=>'pull-left','style'=>'clear:left;margin:10px;'));
    echo Form::text('cache',Setting::get('system.cache'),array('class'=>'col-lg-6-input form-control input-sm pull-right','style'=>'width:240px;'));
    echo "</fieldset>";
                ?>
</div>
</div>
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <?php
    echo Form::submit('Save Changes',array('class'=>'btn btn-success','value'=>'submit'));
                ?>
</div>
</div>
</div>
<?php

echo Form::close();
?>